# version: 2
# sources:
#   - name: crypto_raw
#     database: loyal-weaver-471905-p9 # REPLACE THIS
#     tables:
#       - name: daily_market




version: 2

sources:
  - name: crypto_raw
    database: loyal-weaver-471905-p9
    tables:
      - name: daily_market
        loaded_at_field: loaded_at
        # Indent this block so it belongs to the table
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}